name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Cada día a medianoche UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar Snake
        uses: Platane/snk@master
        with:
          github_user_name: ErickFrancis-22
          outputs: dist/snake.svg

      - name: Subir a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
